title: Arjun Mahanti
description: A multidisciplinary designer building delightful solutions to complex problems. 
baseurl: ""
url: "https://mahanti.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Sass processing
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false